resources:
  requests:
    memory: "7512M"
  limits:
    memory: "8512M"

strategyType: Recreate

livenessProbe:
  command:
    - mc-health
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 20
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  command:
    - mc-health
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 20
  successThreshold: 1
  timeoutSeconds: 1
startupProbe:
  command:
    - mc-health
  enabled: false
  failureThreshold: 30
  periodSeconds: 10

deploymentLabels:
  load-balancer: minecraft
podLabels:
  load-balancer: minecraft

minecraftServer:
  eula: "TRUE"
  version: "1.20.1"
  type: "FORGE"
  forgeVersion: "47.1.33"
  difficulty: normal
  whitelist: "Hamothy_,Aishwxrya"
  ops: "Hamothy_,Aishwxrya"
  viewDistance: 32
  motd: "Criminal Offensive Side-EYE"
  pvp: true
  levelType: DEFAULT
  worldSaveName: ForgeModdedSurvival
  memory: 6512M
  maxWorldSize: 5999968

  rcon:
    enabled: true
    existingSecret: minecraft-rcon
    secretKey: rcon-password

persistence:
  dataDir:
    enabled: true
    Size: 10Gi

mcbackup:
  enabled: true

  image:
    repository: itzg/mc-backup
    tag: latest
    pullPolicy: IfNotPresent

  initialDelay: 2m
  backupInterval: "2h"
  pauseIfNoPlayers: "true"
  pruneBackupsDays: 3
  rconRetries: 5
  rconRetryInterval: 10s
  excludes: "*.jar,cache,logs"
  backupMethod: tar
  destDir: /backups
  linkLatest: "true"
  compressMethod: "zstd"

  resources:
    requests:
      memory: 512Mi

  persistence:
    backupDir:
      enabled: true
      Size: 20Gi
