apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-goudham-com
  namespace: traefik
spec:
  commonName: goudham.com
  dnsNames:
  - goudham.com
  - '*.goudham.com'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: goudham-com-cert