apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: winston-bot
  name: winston-bot
  namespace: winston-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: winston-bot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: winston-bot
    spec:
      containers:
        - image: sgoudham/winston-bot:latest
          imagePullPolicy: Always
          name: winston-bot
          resources: {}
          envFrom:
            - secretRef:
                name: token
            - secretRef:
                name: spotify
      dnsPolicy: ClusterFirst
      restartPolicy: Always
