apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pastebin-pvc
  name: pastebin-pvc
  namespace: pastebin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
