apiVersion: v1
kind: Service
metadata:
  name: minecraft-load-balancer
  namespace: minecraft-server
spec:
  selector:
    cursed: minecraft
  type: LoadBalancer
  ports:
    - name: minecraft
      protocol: TCP
      port: 25565
      targetPort: 25565