# If this option is set to false a StateFulset instead of a Deployment is used
useDeploy: true

podEnv:
  - name: "UPTIME_KUMA_PORT"
    value: "3001"

service:
  type: ClusterIP
  port: 3001

ingress:
  enabled: true
  hosts:
    - host: status.goudham.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - status.goudham.com

resources: {}

livenessProbe:
  enabled: true
  timeoutSeconds: 2
  initialDelaySeconds: 15
readinessProbe:
  enabled: true
  initialDelaySeconds: 5

volume:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi

strategy:
  type: Recreate
